name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  check-workflow-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      - name: Fetch workflow runs from the fork
        id: workflow_runs
        run: |
          FORK_OWNER=$(jq -r .pull_request.head.repo.owner.login < "${{ github.event_path }}")
          FORK_REPO=$(jq -r .pull_request.head.repo.name < "${{ github.event_path }}")
          
          WORKFLOW_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$FORK_OWNER/$FORK_REPO/actions/workflows | jq -r '.workflows[] | select(.path == ".github/workflows/main.yaml") | .id')
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$FORK_OWNER/$FORK_REPO/actions/workflows/$WORKFLOW_ID/runs?per_page=1)
          
          RUN_ID=$(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[0].id')       
          if [ -z "$RUN_ID" ]; then
            echo "No successful workflow runs found in fork."
            exit 1
          fi
          echo "Latest successful workflow run ID: $RUN_ID"

          curl "https://api.github.com/repos/$FORK_OWNER/$FORK_REPO/actions/runs/$RUN_ID/jobs" | jq '.jobs[] | select(.conclusion == "success") | .name'

      - name: Check all jobs in the workflow run
        run: |
          RUN_ID=${{ steps.workflow_runs.outputs.run_id }}
          FORK_OWNER=${{ steps.fork_info.outputs.FORK_OWNER }}
          FORK_REPO=${{ steps.fork_info.outputs.FORK_REPO }}

          # Fetch jobs from the specific workflow run
          JOBS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$FORK_OWNER/$FORK_REPO/actions/runs/$RUN_ID/jobs")

          FAILED_JOBS=$(echo "$JOBS" | jq '[.jobs[] | select(.conclusion != "success")] | length')
          if [ "$FAILED_JOBS" -ne 0 ]; then
            echo "Some jobs have failed in the workflow run!"
            exit 1
          else
            echo "All jobs have completed successfully."
          fi

#      - name: Verify no changes to the workflow file
#        run: |
#          git fetch origin ${{ github.event.pull_request.base.ref }}
#          diff=$(git diff origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} -- name_of_the_workflow_file.yaml)
#
#          if [ -n "$diff" ]; then
#            echo "Workflow file has been modified!"
#            exit 1
#          else
#            echo "No significant changes to the workflow file."
#          fi
