name: Trigger Kata Tests

on:
  push:
    branches:
      - test
#    paths:
#      - 'katas/**'

jobs:
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: install pylint
        run: |
          pip install requests pytube pylint

  ListKatas:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Katas to test
        run: |  
          kata_files=$(find katas/test/ -name 'test_*.py')
          kata_json=$(echo "$kata_files" | jq -R -s -c 'split("\n")[:-1]')
          echo "Katas: $kata_json"
          echo "kata_list=$kata_json" >> $GITHUB_OUTPUT

  test-katas:
    needs: ListKatas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kata_name: ${{ fromJson(needs.ListKatas.outputs.kata_list) }}
    steps:
      - uses: actions/checkout@v2
      - name: Kata Test
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd katas
          cp test/_score.py .
          python _score.py
      - name: Linting Test
        run: |
          cd katas
          pylint *.py || true
