name: Test Katas

on:
  push:
    branches:
      - test
#    paths:
#      - 'katas/**'

jobs:
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: install pylint
        run: |
          pip install requests pytube pylint pytest

  LintTest:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linting Test
        working-directory: katas
        run: |
          pylint *.py || true

  Test:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kata Test
        working-directory: katas
        run: |
          pip install pytest
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest test/ --junitxml=results.xml

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest
          path: katas/results.xml
          reporter: junit