name: Trigger Kata Tests

on:
  push:
    branches:
      - test
#    paths:
#      - 'katas/**'

jobs:
  LintTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linting Test
        working-directory: katas
        run: |
          pip install pylint
          pylint *.py || true

  ListKatas:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.kata_tests.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find Katas to test
        id: kata_tests
        working-directory: katas/test
        run: |  
          kata_json=$(ls test_*.py | jq -R -s -c 'split("\n")[:-1]')
          echo "Katas: $kata_json"
          echo "tests=$kata_json" >> $GITHUB_OUTPUT

  Test:
    needs: ListKatas
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kata_name: ${{ fromJson(needs.ListKatas.outputs.tests) }}
    steps:
      - uses: actions/checkout@v4
      - name: Kata Test
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd katas
          python test/${{ matrix.kata_name }}

  CreateMap:
    needs: Test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Commit and push markers.json to gh-pages
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          touch markers.json
          git add markers.json
          git commit -m "Update markers.json" || echo "No changes to commit"
          git push origin gh-pages # Ensure gh-pages branch exists or create it if necessary

      - name: Notify user about GitHub Pages site
        run: |
          echo "GitHub Pages site created for you! You can view it at: https://<username>.github.io/<repository>/map" >> $GITHUB_ENV
