name: Test Katas

on:
  push:
    branches:
      - test
#    paths:
#      - 'katas/**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: install pylint
        run: |
          pip install requests pytube pylint pytest

  LintTest:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Linting Test
        working-directory: katas
        run: |
          pylint *.py || true

  Test:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kata Test
        working-directory: katas
        run: |
          pip install pytest
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest test/ --junitxml=results.xml --junit-prefix="KatasTest"


      - name: list success
        working-directory: katas
        if: always()
        run: |
          grep -oP '(?<=<testcase name=")[^"]+' results.xml | grep -vP '(?<=</failure>)'



      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: katas/results.xml

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Summary
          path: katas/results.xml
          reporter: java-junit
          fail-on-error: false
          max-annotations: '50'
