name: Trigger Kata Tests

on:
  push:
    branches:
      - test
#    paths:
#      - 'katas/**'

jobs:
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: install pylint
        run: |
          pip install requests pytube pylint

  LintTest:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    steps:
      - name: Linting Test
        run: |
          cd katas
          pylint *.py || true


  ListKatas:
    needs: InstallDependencies
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.kata_tests.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Katas to test
        id: kata_tests
        working-directory: katas/test
        run: |  
          kata_json=$(ls test_*.py | jq -R -s -c 'split("\n")[:-1]')
          echo "Katas: $kata_json"
          echo "tests=$kata_json" >> $GITHUB_OUTPUT

  test:
    needs: ListKatas
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kata_name: ${{ fromJson(needs.ListKatas.outputs.tests) }}
    steps:
      - uses: actions/checkout@v2
      - name: Kata Test
        working-directory: katas
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python ${{ matrix.kata_name }}

